version: '3.7'

services:
  web:
    build: .
    command: gunicorn drfx.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=drfx
      - POSTGRES_PASSWORD=drfx
      - POSTGRES_DB=drfx_dev

volumes:
  postgres_data:
